### ISSUE TITLE
Running Test Framework triggers a Part-o-Magic Error

### ISSUE THREAD

**Issue by luzpaz** [DeepSOIC/Part-o-magic#31]
Reproduce:
1. Switch to 'Test framework' workbench  
2. Start `Self-test`  
Result:  
```
Traceback (most recent call last):
  File "/home/foo/.FreeCAD/Mod/Part-o-magic/PartOMagic/Gui/Observer.py", line 133, in slotChangedObject
    lmd()
  File "/home/foo/.FreeCAD/Mod/Part-o-magic/PartOMagic/Gui/Observer.py", line 116, in <lambda>
    self.appendToActiveContainer(feature, ac, aw)
  File "/home/foo/.FreeCAD/Mod/Part-o-magic/PartOMagic/Gui/Observer.py", line 329, in appendToActiveContainer
    if test_exclude(feature, active_workbench):
  File "/home/foo/.FreeCAD/Mod/Part-o-magic/PartOMagic/Gui/Observer.py", line 39, in test_exclude
    if feature.isDerivedFrom(typ):
<class 'ReferenceError'>: Cannot access attribute 'isDerivedFrom' of deleted object
```

OS: Manjaro Linux (XFCE/xfce)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.17068 (Git) AppImage
Build type: Release
Branch: master
Hash: 236f890864ef51a8a09b7e507a3a122c41fbb724
Python version: 3.7.1
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)

**Comment by DeepSOIC** [comment]
I know. Sorry, I probably can't fix it. I can only silence it.

**Comment by luzpaz** [comment]
@DeepSOIC Is it a time issue, or know-how? Why won't you fix it?

**Comment by DeepSOIC** [comment]
Well, if it is possible, it adds quite a lot of unnecessary complexity. Since it doesn't crash FreeCAD (as far as I know), it is not worth the trouble. I can "fix" it by just handling the error and thus silencing it, but that comes at a cost of potentially silencing the error for a case where it is a problem. Well, I'll think about it, maybe I will fix it after all...

That bug is caused by some delayed actions. E.g. this one appears to come from the mechanism for automatic tip advancement, where PoM waits for a little, to analyze the object when it's fully set up. In tests, the object just disappears too fast.
